#!/usr/bin/perl -w
use strict;
use Getopt::Long;
use Cwd 'getcwd';

my %opts;
GetOptions(\%opts,"g=s","r=s","o=s","h|help");
if (!( defined $opts{g} and defined $opts{r} and defined $opts{o})) {
		die "************************************************\n
	-g	Full path to the [gffs_S10] directory
	-r	Full path to the [Results_*] directory generated by [OrthoFinder]
	-o	Full path to the [outputDir_S10] directory
	Optional:
	-h|-help Print this help page
		*************************************************\n";
}
if (defined $opts{h} or defined $opts{help}) {
		die "************************************************\n
	-g	Full path to the [gffs_S10] directory
	-r	Full path to the [Results_*] directory generated by [OrthoFinder]
	-o	Full path to the [outputDir_S10] directory
	Optional:
	-h|-help Print this help page
		*************************************************\n";
}
my $old_dir = getcwd();

my $slash;
####
if ($opts{g} =~ /(\/)$/) {
    # 存储捕获的结果
    $slash = $1;

    # 删除末尾的 /
    $opts{g} =~ s/$slash$//;
}
####

####
if ($opts{r} =~ /(\/)$/) {
    # 存储捕获的结果
    $slash = $1;

    # 删除末尾的 /
    $opts{r} =~ s/$slash$//;
}
####
if ($opts{o} =~ /(\/)$/) {
    # 存储捕获的结果
    $slash = $1;

    # 删除末尾的 /
    $opts{o} =~ s/$slash$//;
}
####

######################

my $dir = "$opts{o}"; 

opendir my $dh, $dir or die "can't open $dir: $!";

my @files = readdir($dh);       
closedir($dh);   

if (@files == 2) {
} 
else {
	system "rm -r $opts{o}/*";
}

#######################

#################################################
my $dir1=$opts{g};
open O,">$opts{o}/all.gff";
opendir P,$dir1;
while (my $c=readdir P) {
	if ($c=~/^(\S+)_simplified.gff$/) {
		my $name=$1;
		my $file=$dir1."/$c";
		open I,"<$file" or die("Could not open $file\n"); 
		while (my $a=<I>) {
			chomp $a;
			my @it=split/\t/,$a;
			print O "$name\_$it[0]\t$it[1]\t$it[2]\t$it[3]\n";
		}
		close I;
	}
}
close P;close O;
system "cp $opts{r}/WorkingDirectory/SequenceIDs.txt $opts{o}";
system "cp $opts{r}/WorkingDirectory/SpeciesIDs.txt $opts{o}";
system "cp $opts{r}/WorkingDirectory/Blast* $opts{o}";
chdir "$opts{o}";
system "gunzip *.gz";
system "cat Blast*>data.blast";
system "rm Blast*";
chdir "$old_dir";
system "cp $opts{r}/Orthogroups/Orthogroups.tsv $opts{o}";

chdir "$opts{o}";
system "pSONIC data translate_gff -gff all.gff";
system "MCScanX data -b 2";
system "pSONIC data";
