#!/usr/bin/perl -w
#use strict;
use Getopt::Long;
my %opts;
GetOptions(\%opts,"i=s","o=s");
if(!(defined $opts{i} and defined $opts{o})){

	die"**********************************************\n
	options:
		-i	Full path to the [APCF_*.merged.map] file (generated by DESCHRAMBLER software)
		-o	Full path to the output file (e.g. /custom_path/HSap.block)
		*********************************************\n";
}

my %h1;
open I,"<$opts{i}";
open O,">$opts{o}";

while ($a=<I>){
	chomp $a;
	if ($a=~/^APCF\.(\S+):/) {
		$block_name=$1;
	}
	if ($a!~/>/) {
		if ($a!~/APCF/) {
			if ($a=~/:/) {
				my @items=split/ /,$a;
				my $chr=$items[0];
				if ($chr=~/\.(\S+):(\S+)-(\S+)/) {
					print O "$block_name\t$1\t$2\t$3\n";
				}
			}
		}
	}
}
close O;
close I;